name: myanimelist
description: The best way to explore all anime and manga.

publish_to: 'none'

version: 1.2.3+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  dynamic_theme:
    git: git://github.com/Norbert515/dynamic_theme.git
  url_launcher: ^6.0.20
  charts_flutter: ^0.12.0
  expandable: ^5.0.1
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^9.2.0
  package_info_plus: ^1.3.0
  page_indicator: ^0.4.1
  cloud_firestore: ^3.1.8
  firebase_analytics: ^9.1.0
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  firebase_performance: ^0.8.0
  firebase_remote_config: ^2.0.0
  jikan_api: ^1.6.1
  slack_notifier: ^1.1.0
  rate_my_app: ^1.1.1
  photo_view: ^0.13.0
  xml: ^5.3.1
  fluttertoast: ^8.0.8
  flutter_web_auth: ^0.4.0
  flutter_pagewise:
    git: git://github.com/javoeria/flutter_pagewise.git

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.2

flutter_icons:
  android: true
  ios: false
  image_path: "images/maneki.png"

flutter_native_splash:
  android: true
  ios: false
  image: "images/maneki.png"
  color: "f5f5f5"

flutter:
  uses-material-design: true
  assets:
    - images/
