name: myanimelist
description: The best way to explore all anime and manga.

version: 1.1.1+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  provider: ^4.3.2
  shared_preferences: ^0.5.12
  dynamic_theme: ^1.0.1
  url_launcher: ^5.7.10
  charts_flutter: ^0.9.0
  expandable: ^4.1.4
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.11.0
  package_info: ^0.4.3
  page_indicator: ^0.3.0
  cloud_firestore: ^0.14.4
  # firebase_admob: ^0.10.3
  firebase_analytics: ^6.3.0
  firebase_core: ^0.5.3
  firebase_crashlytics: ^0.2.4
  firebase_performance: ^0.4.3
  # firebase_remote_config: ^0.4.3
  jikan_api: ^1.5.0
  slack_notifier: ^1.0.0
  rate_my_app: ^0.7.2
  fluttertoast: ^7.1.6
  flutter_web_auth: ^0.2.4
  flutter_pagewise:
    git: git://github.com/javoeria/flutter_pagewise.git

dev_dependencies:
  pedantic: ^1.9.2
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9
  flutter_driver:
    sdk: flutter
  test: any

flutter_icons:
  android: true
  ios: false
  image_path: "images/maneki.png"

flutter_native_splash:
  android: true
  ios: false
  image: "images/maneki.png"
  color: "f5f5f5"

flutter:
  uses-material-design: true

  assets:
    - images/
