name: myanimelist
description: The best way to explore all anime and manga.

publish_to: 'none'

version: 1.2.1+12

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  provider: ^5.0.0
  shared_preferences: ^2.0.7
  dynamic_theme:
    git: git://github.com/Norbert515/dynamic_theme.git
  url_launcher: ^6.0.9
  charts_flutter: ^0.11.0
  expandable: ^5.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  font_awesome_flutter: ^9.1.0
  package_info: ^2.0.2
  page_indicator: ^0.4.1
  cloud_firestore: ^2.5.1
  firebase_analytics: ^8.3.1
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_performance: ^0.7.0
  firebase_remote_config: ^0.10.0
  jikan_api: ^1.6.0
  slack_notifier: ^1.1.0
  rate_my_app: ^1.1.1
  photo_view: ^0.12.0
  xml: ^5.1.2
  fluttertoast: ^8.0.8
  flutter_web_auth: ^0.3.0
  flutter_pagewise:
    git: git://github.com/javoeria/flutter_pagewise.git

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.1

flutter_icons:
  android: true
  ios: false
  image_path: "images/maneki.png"

flutter_native_splash:
  android: true
  ios: false
  image: "images/maneki.png"
  color: "f5f5f5"

flutter:
  uses-material-design: true
  assets:
    - images/
