name: myanimelist
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  intl: ^0.15.8
  provider: ^3.1.0
  shared_preferences: ^0.5.3+4
  dynamic_theme: ^1.0.1
  url_launcher: ^5.1.4
  charts_flutter: ^0.8.1
  expandable: ^3.0.0+1
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.5.0
  package_info: ^0.4.0+6
  page_indicator: ^0.3.0
  cloud_firestore: ^0.12.9+5
  #firebase_admob: ^0.9.0+7
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  firebase_crashlytics: ^0.1.0+3
  firebase_performance: ^0.3.0+5
  firebase_remote_config: ^0.2.0+7
  jikan_dart:
    path: ../jikan-dart/
  flutter_pagewise:
    path: ../flutter_pagewise/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  assets:
    - images/
