name: myanimelist
description: The best way to explore all anime and manga.

publish_to: 'none'

version: 1.3.0+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  charts_flutter: ^0.12.0
  cloud_firestore: ^3.4.6
  dynamic_theme:
    git: https://github.com/Norbert515/dynamic_theme.git
  expandable: ^5.0.1
  firebase_analytics: ^9.3.3
  firebase_core: ^1.21.1
  firebase_crashlytics: ^2.8.9
  firebase_performance: ^0.8.2
  firebase_remote_config: ^2.0.16
  flutter_pagewise:
    git: https://github.com/javoeria/flutter_pagewise.git
  flutter_web_auth: ^0.4.1
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  jikan_api: ^2.0.0
  package_info_plus: ^1.4.3
  page_indicator: ^0.4.1
  photo_view: ^0.14.0
  provider: ^6.0.3
  rate_my_app: ^1.1.3
  shared_preferences: ^2.0.15
  slack_notifier: ^1.2.0
  url_launcher: ^6.1.5
  xml: ^6.1.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.8

flutter_icons:
  android: true
  ios: false
  image_path: "images/maneki.png"

flutter_native_splash:
  android: true
  ios: false
  image: "images/maneki.png"
  color: "f5f5f5"

flutter:
  uses-material-design: true
  assets:
    - images/
