name: myanimelist
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  intl: ^0.16.0
  provider: ^3.2.0
  shared_preferences: ^0.5.6
  dynamic_theme: ^1.0.1
  url_launcher: ^5.4.1
  charts_flutter: ^0.8.1
  expandable: ^4.0.1
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.5.0
  package_info: ^0.4.0+13
  page_indicator: ^0.3.0
  cloud_firestore: ^0.13.0+1
  #firebase_admob: ^0.9.0+10
  firebase_analytics: ^5.0.9
  firebase_core: ^0.4.3+1
  firebase_crashlytics: ^0.1.2+4
  firebase_performance: ^0.3.1+5
  #firebase_remote_config: ^0.3.0+1
  jikan_api: ^1.1.0
  flutter_pagewise:
    git: git://github.com/javoeria/flutter_pagewise.git

dev_dependencies:
  pedantic: ^1.8.0
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter_icons:
  android: true
  ios: false
  image_path: "images/icon.png"

flutter_native_splash:
  android: true
  ios: false
  image: "images/splash.png"
  color: "f5f5f5"

flutter:
  uses-material-design: true

  assets:
    - images/
